apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-db"
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: "{{ .Release.Name }}-db"